assignments/urls.py
from django.urls import re_path, path
from assignments import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

app_name = 'assignments'
urlpatterns = [
    re_path(r'^create/$', views.CreateAssignment.as_view(), name="create"),
    re_path(r'^detail/(?P<pk>[-\w]+)/$', views.AssignmentDetail.as_view(), name='detail'),
    re_path(r'^update/(?P<pk>[-\w]+)/$', views.UpdateAssignment.as_view(), name='update'),
    re_path(r'^delete/(?P<pk>[-\w]+)/$', views.DeleteAssignment.as_view(), name="delete"),
    re_path(r'^submit/$', views.SubmitAssignmentView.as_view(), name="submit"),
    re_path(r'^submission/detail/(?P<pk>[-\w]+)/$', views.SubmitAssignmentDetail.as_view(), name="submit_detail"),
    re_path(r'^submission/delete/(?P<pk>[-\w]+)/$', views.delete_view, name="submit_delete"),
    re_path(r'^grade/(?P<pk>[-\w]+)/$', views.grade_assignment, name='grade'),
    path('create_quiz/', views.create_quiz, name='create_quiz'),
    path('create_question/<int:quiz_id>/', views.CreateQuestionView.as_view(), name='create_question'),
    path('create_question/', views.CreateQuestionViewWithoutId.as_view(), name='create_question_without_id'),
    # path('submit_quiz/<int:quiz_id>', views.QuizAnswerView.as_view(), name='submit_quiz'),
    re_path(r'^submit_quiz/(?P<quiz_id>\d+)/$', views.QuizAnswerView.as_view(), name='submit_quiz'),
    path('quiz/results/<int:submission_id>/<int:quiz_id>/', cache_page(60*60)(views.QuizResultsView.as_view()), name='quiz_results'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

courses/urls.py
# from django.conf.urls import url
from django.urls import re_path, path
from courses import views

from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

app_name = "courses"

urlpatterns = [
    re_path(r'^new/$', views.CreateCourse.as_view(), name="create"),
    # re_path(r'^detail/(?P<pk>[-\w]+)/$', views.CourseDetail.as_view(), name='detail'),
    path("detail/<int:pk>/", views.CourseDetail.as_view(), name="detail"),
    path('all/', views.ListCourse.as_view(), name="list"),
    path('course_info/<int:pk>/', views.CourseInfoView.as_view(), name='course_info'),
    re_path(r'^enroll/(?P<pk>[-\w]+)/$', views.EnrollCourse.as_view(), name='enroll'),
    re_path(r'^unenroll/(?P<pk>[-\w]+)/$', views.UnenrollCourse.as_view(), name='unenroll'),
    path('create_chapter/', views.CreateChapterView.as_view(), name='create_chapter'),
    path('create_lesson/', views.CreateLessonView.as_view(), name='create_lesson'),
    path('update_chapter/<int:pk>/', views.UpdateChapterView.as_view(), name='update_chapter'),
    path('update_lesson/<int:pk>/', views.UpdateLessonView.as_view(), name='update_lesson'),
    path('update_course/<int:pk>/', views.UpdateCourseView.as_view(), name='update_course'),
    path('completed_lessons_count/<int:course_id>/', views.get_completed_lessons_count, name='completed_lesson_count'),
    # path('completed_lesson_count/<int:pk>/', views.CourseDetail.as_view(), name='completed_lesson_count'),
    path('mark_lesson_as_complete/', views.mark_lesson_as_complete, name='mark_lesson_as_complete'),
    path('certificate/<int:course_id>/', views.certificate_view, name='certificate'),
    path('update_video_progress/', views.update_video_progress, name='update_video_progress'),
    path('verify_certificate/', views.verify_certificate, name='verify_certificate'),
    path('achievements/', views.achievements, name='achievements'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url, include
from django.urls import re_path
from assignments import views
from django_lms import views as views_project
from django_lms import views as project_views
from graphene_django.views import GraphQLView
from django.views.decorators.cache import cache_page

from graphene_file_upload.django import FileUploadGraphQLView
from .views import get_calendar_events



urlpatterns = [
    re_path(r'^$', project_views.index, name="home"),
    path('admin/', admin.site.urls),
    re_path(r'^users/', include('users.urls', namespace='users')),
    re_path(r'^courses/', include('courses.urls', namespace="courses")),
    re_path(r'^assignments/', include('assignments.urls', namespace='assignments')),
    re_path(r'^resources/', include('resources.urls', namespace="resources")),
    re_path(r'^editor/', include('editor.urls', namespace="editor")),
    path('user_profile/<int:pk>/',cache_page(60*60)(project_views.UserProfile.as_view()), name='profile'),

    re_path('graphql/', FileUploadGraphQLView.as_view(graphiql=True)),
    path("__reload__/", include("django_browser_reload.urls")),
    path('send-chatbot-response/', views_project.send_chatbot_response, name='chattext'),
    path('markdownx/', include('markdownx.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('calendar/', get_calendar_events, name='calendar'),
    path('accounts/', include('allauth.urls')),


    # path('', include('admin_material.urls')),
    # path('api-auth/', include('rest_framework.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import re_path,path
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

urlpatterns = [
    # re_path(r'login/$', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    # re_path(r'logout/$', auth_views.LogoutView.as_view(), name="logout"),
    # re_path(r'signup/$', views.SignUp.as_view(), name='signup'),
    path('signup/', views.CustomSignUpView.as_view(), name='signup'),
    re_path(r'contact/$', views.Contact, name='contact'),
]

assignments/models.py
from django.db import models
from users.models import User
from courses.models import Course, Chapter
from django.urls import reverse
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
import os
from django.conf import settings
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class Assignment(models.Model):
    assignment_name = models.CharField(max_length=200, blank=False)
    assignment_description = models.TextField(blank=False)
    start_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.assignment_name

    def get_absolute_url(self):
        return reverse('assignments:detail', kwargs={'pk': self.pk})

class Quiz(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    chapter = models.ForeignKey(Chapter, related_name="chapter_quizzes", on_delete=models.CASCADE)
    quiz_title = models.CharField(max_length=200, unique=True)
    quiz_description = models.TextField()

    def __str__(self):
        return self.quiz_title
    
class CompletedQuiz(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    completed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'quiz')
# class UserProfile(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     completed_quizzes = models.ManyToManyField(Quiz, related_name='completed_by_users', blank=True)

class Question(models.Model):
    quiz_title = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.TextField()

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name="choice",on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

class QuizSubmission(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='quiz', on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.PositiveIntegerField()
    submitted_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student.username} - {self.quiz.quiz_title} - Score: {self.score}"
    class Meta:
        unique_together = ('student', 'quiz')
    
class SubmitAssignment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='assignment', on_delete=models.CASCADE)
    topic = models.CharField(max_length=200, blank=False)
    description = models.TextField(blank=False)
    assignment_file = models.FileField(blank=False, upload_to='assignments')
    submitted_date = models.DateTimeField(default=timezone.now)
    assignment_ques = models.ForeignKey(Assignment, related_name="question", on_delete=models.CASCADE, null=True)
    graded = models.BooleanField(default=False)
    grade = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)
        ]
    )

    def __str__(self):
        return self.topic

    def grade_assignment(self, grade):
        self.grade = grade
        self.graded = True
        self.save()

    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.assignment_file.name))
        super().delete(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('assignments:submit_detail', kwargs={'pk': self.pk})

assignments/forms.py
from django.forms import ModelForm, DateInput, TimeInput, Form, DateTimeInput, modelformset_factory
from django import forms
from django.shortcuts import get_object_or_404
from assignments.models import SubmitAssignment, Assignment, Quiz, Question, Choice, QuizSubmission
from django.utils import timezone
from courses.models import Course
from users.models import User

class GradeAssignmentForm(ModelForm):
    
    class Meta:
        model = SubmitAssignment
        fields = ['grade']

class CreateAssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ('assignment_name', 'assignment_description',
                  'due_date', 'course')
        labels = {
            'due_date': 'Due Date (yyyy-mm-dd HH:MM)'
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        user_object = User.objects.filter(username=user.username)
        new_user_object = get_object_or_404(user_object)
        self.fields['course'].queryset = self.fields['course'].queryset.filter(teacher=new_user_object.id)

class SubmitAssignmentForm(ModelForm):
    class Meta:
        model = SubmitAssignment
        fields = ('topic', 'description', 'assignment_file', 'assignment_ques', 'author')
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        assignment = kwargs.pop('assignment_id')
        super().__init__(*args, **kwargs)
        self.fields['assignment_ques'].queryset = self.fields['assignment_ques'].queryset.filter(pk=assignment)
        self.fields['author'].queryset = self.fields['author'].queryset.filter(username=user.username)

class SubmitQuizForm(ModelForm):
    class Meta:
        model = QuizSubmission
        fields = ('quiz', 'student', 'score')
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        quiz = kwargs.pop('quiz_id')
        super().__init__(*args, **kwargs)
        self.fields['quiz'].queryset = self.fields['quiz'].queryset.filter(pk=quiz)
        self.fields['student'].queryset = self.fields['student'].queryset.filter(username=user.username)

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['course','chapter','quiz_title', 'quiz_description']
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        user_object = User.objects.filter(username=user.username)
        new_user_object = get_object_or_404(user_object)
        self.fields['course'].queryset = self.fields['course'].queryset.filter(teacher=new_user_object.id)
        self.fields['chapter'].queryset = self.fields['chapter'].queryset.filter(course__teacher=new_user_object.id)

class QuestionTextAndChoicesWidget(forms.MultiWidget):
    def __init__(self, question_text, choices, attrs=None):
        widgets = (
            forms.RadioSelect(choices=choices),
            forms.HiddenInput()
        )
        super().__init__(widgets, attrs)
        self.question_text = question_text

    def decompress(self, value):
        if value:
            return [None, value]
        return [None, None]

class QuizAnswerForm(forms.Form):
    def __init__(self, *args, **kwargs):
        quiz_id = kwargs.pop('quiz_id')
        super().__init__(*args, **kwargs)
        questions = Question.objects.filter(quiz_title_id=quiz_id)
        for question in questions:
            choices = [(choice.id, choice.text) for choice in question.choice.all()]
            field_name = f'question_{question.id}_choice'
            self.fields[field_name] = forms.ChoiceField(
                choices=choices,
                widget=forms.RadioSelect,
                label=question.question_text
            )


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['quiz_title', 'question_text']

        


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['question', 'text', 'is_correct']

assignments/templates/assignments/assignment_base.html
{% extends 'base.html' %}


{% block title %}
    
    {% block title_name %}
        
    {% endblock title_name %}
        
{% endblock title %}
    

{% block body_content %}
    
    {% block main_content %}
    
    {% endblock main_content %}

{% endblock body_content %}
    

    

assignments/templates/assignments/assignment_detail.html
{% extends 'assignments/assignment_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - {{assignment.assignment_name}}
{% endblock title_name %}
    

{% block main_content %}
    <div class="p-5 shadow-lg rounded-lg w-[70%] mt-[150px] text-cyan-950">
        <h1  class="font-sans font-semibold text-4xl">{{assignment.assignment_name}}</h1>
        <h4 class="font-serif font-semibold">Course: {{assignment.course}}</h4>
        <h6 class="font-extralight">Start Date: {{assignment.start_date}}</h6>
        <h6 class="font-extralight">Due Date: {{assignment.due_date}}</h6>
        
        <p class="font-extralight">Description: {{assignment.assignment_description}}</p>
        {% if user.user_type == 2 %}
            <a href="{% url 'assignments:update' pk=assignment.pk %}" class="bg-cyan-950 m-2 text-white hover:bg-yellow-500 p-2 rounded-md hover:no-underline text-md font-extrabold ">Update</a>
            <a href="{% url 'assignments:delete' pk=assignment.pk %}" class="bg-red-700 m-2 text-white hover:bg-red-600 p-2 rounded-md text-md font-extrabold hover:no-underline">Delete</a>

            <div class="submissions">
            <h3  class="font-sans font-semibold text-4xl">Submissions</h3>
            {% for submissions in submitted %}
                <a href="{% url 'assignments:submit_detail' pk=submissions.pk %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{submissions.topic}}</h5>
                    <small>{{submissions.author}}</small>
                    </div>
                    <p class="mb-1">
                    {{submissions.description}}
                    </p>
                    <small>Start Date: {{submissions.submitted_date}}</small><br>
                </a>
            {% empty %}
                <h6>No Submissions</h6>
            {% endfor %}
            </div>
                

        {% else %}            
            {% if assignment.course in course %}
                {% if duedate >= time %}

                    <a href="{% url 'assignments:submit' %}" class="bg-cyan-950 hover:text-white text-gray-100 hover:bg-yellow-500 hover:outline-none p-2 rounded-lg text-md font-extrabold hover:no-underline">Submit Assignment</a>
                {% endif %}
                <div class="submissions">
                <h3 class="font-sans font-semibold text-3xl m-2">My Submissions:</h3>
                
                {% for submissions in submitted %}
                    {% if submissions.author.id == user.id %}
                        <a href="{% url 'assignments:submit_detail' pk=submissions.pk %}" class="list-group-item list-group-item-action rounded-lg bg-transparent shadow-sm outline-none border-none">
                            <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1 uppercase font-semibold">{{submissions.topic}}</h5>
                            <small>{{submissions.author}}</small>
                            </div>
                            <p class="mb-1">
                            {{submissions.description}}
                            </p>
                            <small>Start Date: {{submissions.submitted_date}}</small><br>
                        </a>
                    {% endif %}
                {% empty %}
                    <h6 class="m-2 font-extralight">No Submissions</h6>
                {% endfor %}
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock main_content %}
    

assignments/templates/assignments/create_assignment_form.html
{% extends 'assignments/assignment_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
  LMS - Create Resource
{% endblock title_name %}
  
{% block main_content %}

<div class="text-cyan-950 mt-[150px] w-[72%]">
  <h1 class="font-sans font-semibold text-3xl m-2">Assignment</h1>

  {% if user.user_type == 2 %}
    <form method="POST" action="{% url 'assignments:create' %}" class="shadow-lg p-4 rounded-xl font-sans font-semibold m-2">
      {% csrf_token %} 
      {% bootstrap_field form.assignment_name %}
      {% bootstrap_field form.assignment_description %}
      {% bootstrap_field form.due_date %}
      {% bootstrap_field form.course %}
      {{ form.name.errors }}
      <input type="submit" value="Submit" class="bg-cyan-950 m-2 text-white hover:bg-yellow-500 p-2 rounded-md text-md font-extrabold hover:no-underline">
    </form>
    
    
    {% else %}
        <div class="jumbotron">
            <h2>You cannot create an assignment</h2>
        </div>
    {% endif %}

</div>
{% endblock main_content %}

assignments/templates/assignments/create_question.html
{% extends 'assignments/assignment_base.html' %}
{% load widget_tweaks %}
{% load bootstrap4 %}

{% block title_name %}
  LMS - Create-Questions
{% endblock title_name %}

{% block main_content %}

<div class="w-[72%] mt-[150px] pl-5">
  <h1 class="font-sans font-semibold text-3xl m-2">Set Questions</h1>

  {% if user.user_type == 2 %}
    <form method="POST" action="" class="shadow-lg p-4 rounded-xl font-sans font-semibold m-2">
      {% csrf_token %} 
      {% bootstrap_field form.quiz_title %}
      {% bootstrap_field form.question_text %}

      {{ choice_formset.management_form }}
  <!-- Render each form in the choice_formset using Bootstrap classes -->
  {% for form in choice_formset %}
  
  <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {% comment %} {{ form.text.label_tag }} {% endcomment %}
            <label for="{{ form.id_for_label }}">Choice {{ forloop.counter|add:0 }}:</label>
            {{ form.text|add_class:"form-control" }}
            
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.is_correct.label_tag }}
            {{ form.is_correct}}
        </div>
    </div>
</div>
  {% endfor %}

      {{ form.name.errors }}
      <input type="submit" value="Create Another Question" class="bg-cyan-950 m-2 text-white hover:bg-yellow-500 p-2 rounded-md text-md font-extrabold hover:no-underline">
      {% comment %} blue boootstrap button with hover effect {% endcomment %}


      <button name ="finish" class ="bg-yellow-500 hover:bg-yellow-400 p-2 rounded-lg"><a href="{% url 'courses:list' %}" class="hover:no-underline text-gray-100">Finish</a><button>
    </form>


    {% else %}
        <div class="jumbotron">
            <h2>You cannot set questions</h2>
        </div>
    {% endif %}

</div>
{% endblock main_content %}

assignments/templates/assignments/quiz_answer.html
{% extends 'assignments/assignment_base.html' %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{% load custom_tags %}

{% block title_name %}
  Answer Quiz
{% endblock title_name %}

{% block main_content %}

<div class="mt-[150px] text-cyan-950 w-[70%] ml-3 p-4">
  <h2 class="font-semibold">Quiz Title:
    {% if quiz_title %}
        <span class="underline ml-2">{{ quiz_title }}</span>
    {% else %}
        Error: quiz.quiz_title is None
    {% endif %}
    </h2><form method="post" class="p-4 bg-gray-100 rounded-lg font-sans" action="{% url 'assignments:submit_quiz' quiz_id=quiz_id %}">
    {% csrf_token %}
    {{ form }} 
    <button class="m-2 p-2 text-lg font-sans font-semibold bg-cyan-950 text-gray-100 hover:outline-none hover:bg-yellow-500 rounded-lg" type="submit">Submit Answers</button>
</form>
</div>
{% endblock %}

assignments/templates/assignments/quiz_results.html
{% extends 'assignments/assignment_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
  Quiz Results
{% endblock title_name %}

{% block main_content %}
  <div class="p-4 text-cyan-950 bg-white rounded-lg shadow-md mt-[145px] ml-3 w-[70%]">
    <h1 class="text-2xl font-semibold mb-4">Quiz Results</h1>
    <p class="mb-2"><span class="font-semibold">Username:</span> {{ submission.student.username }}</p>
    <p class="mb-2"><span class="font-semibold">Quiz Title:</span> {{ submission.quiz }}</p>
    <p class="mb-4"><span class="font-semibold">Score:</span> {{ submission.score }}</p>

    {% with total_questions=submission.quiz.question_set.count %}
      {% if completed_quizzes %}
        {# User has completed quizzes, redirect to courses list #}
        <a href="{% url 'courses:list' %}" class="text-blue-500 hover:underline">Back to Courses</a>
      {% else %}
        {# User hasn't completed quizzes #}
        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              {% if message.tags %}
                {% if message.tags == 'success' %}
                  <li class="{{ message.tags }} text-green-500">
                    <span>{{ message }}</span>
                    <a class="hover:cursor-pointer underline" href="{% url 'courses:list' %}">Back to Courses</a>
                  </li>
                {% elif message.tags == 'warning' %}
                  <li class="{{ message.tags }} text-red-500">
                    <span>{{ message }}</span>
                    {% comment %} <a class="hover:cursor-pointer underline" href="">Retake Quiz</a> {% endcomment %}
                    Link to retake quiz if attempts remaining
                    {% comment %} {% if remaining_attempts > 0 %} {% endcomment %}
                      <a class="hover:cursor-pointer underline" href="{% url 'assignments:submit_quiz' quiz_id=quiz_id %}">Retake Quiz</a>
                    {% comment %} {% else %}
                      No attempts remaining
                      No attempts remaining.
                    {% endif %} {% endcomment %}
                  </li>
                {% elif message.tags == 'info' %}
                  <li class="{{ message.tags }} text-blue-500">
                    <span>{{ message }}</span>
                    {# Additional info or link if needed #}
                  </li>
                {% endif %}
              {% else %}
                {# Default success message #}
                <li class="text-green-500">
                  <span>{{ message }}</span>
                  <a class="hover:cursor-pointer" href="{% url 'courses:detail' ccourse_id=course_id %}">Back to Course</a>
                </li>
              {% endif %}
            {% endfor %}
          </ul>
        {% endif %}
      {% endif %}
    {% endwith %}

  </div>
{% endblock %}

assignments/templates/assignments/submitassignment_detail.html
{% extends 'assignments/assignment_base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - {{submissions.topic}}
{% endblock title_name %}
    


{% block main_content %}
    <div class="text-cyan-950 mt-[150px] p-4 w-[70%] ml-2">
        {% if submissions.assignment_ques.course.teacher.id == user.id or submissions.author.id == user.id %}
            <h1 class="font-sans font-semibold text-3xl m-2 uppercase">{{submissions.topic}}</h1>
            <h4 class="m-2 text-xl">Submitted by: {{submissions.author}}</h4>
            <h6 class="m-2 text-xl">Submitted On: {{submissions.submitted_date}}</h6>
            <p class="m-2 text-xl font-extralight">Description: {{submissions.description}}</p>
            <p class="m-2 text-xl">Submission: {{submissions.assignment_file.name}}</p>
             
            <a href="{{submissions.assignment_file.url}}" class="bg-cyan-950 m-2 text-white hover:bg-yellow-500 hover:outline-none p-2 rounded-md text-md font-extrabold hover:no-underline" download>Download</a>
            <div class="grade">
                {% if submissions.graded == False %}
                    <p>This assignment has not been graded yet.</p>
                {% else %}
                    <p>This assignment has been graded.</p>
                    <p>Grade: {{submissions.grade}}</p>
                {% endif %}
            </div>
                
            
            
            {% if user.user_type == 1 and submissions.graded == False %}
                <div>
                    <form method="POST">
                        {% csrf_token %}
                        <a href="{% url 'assignments:submit_delete' pk=submissions.pk %}" 
                        class="bg-red-600 m-2 text-white hover:bg-red-800 p-2 rounded-md text-md font-extrabold hover:no-underline">Delete</a>
                    </form>
                    
                </div>
            {% else %}
                
                {% if submissions.assignment_ques.course.teacher.id == user.id %}
                    {% if submissions.graded == False %}
                        <div>
                            <a href="{% url 'assignments:grade' pk=submissions.pk %}" 
                            class="btn btn-success btn-lg">Grade</a>
                        </div>
                    {% endif %}
                {% endif %}

            {% endif %}
                
        {% else %}
            <div class="jumbotron">
                <h2>You cannot view this assignment.</h2>
            </div>
        {% endif %}
    </div>
{% endblock main_content %}
    

assignments/templates/assignments/submitassignment_form.html
{% extends 'assignments/assignment_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Submit Assignment
{% endblock title_name %}
    
{% block main_content %}
    
    {% if user.user_type == 2 %}
        <div class="container">
            <div class="jumbotron">
                <h2>Only students are allowed to submit assignments</h2>
            </div>
        </div>
    {% else %}
            
        <div class="w-[70%] text-cyan-950 p-4 mt-[150px]">
            <h2 class="font-sans font-semibold text-3xl m-2">Submit Assignment</h2>
            <form action="{% url 'assignments:submit' %}" method="POST" enctype="multipart/form-data" class="shadow-lg p-4 rounded-xl font-sans font-semibold m-2">
                {% csrf_token %}
                {% bootstrap_form form %}
                {{ form.name.errors }}
                
                {% if duedate >= time %}
                    <input type="submit" value="Submit" class="bg-cyan-950 m-2 text-white hover:bg-yellow-500 hover:outline-none p-2 rounded-md text-md font-extrabold hover:no-underline">
                {% endif %}
            </form>
            <ul>
            </ul> 
        </div>
    {% endif %}
        
{% endblock main_content %}
    