courses/urls.py
# from django.conf.urls import url
from django.urls import re_path, path
from courses import views

from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

app_name = "courses"

urlpatterns = [
    re_path(r'^new/$', views.CreateCourse.as_view(), name="create"),
    # re_path(r'^detail/(?P<pk>[-\w]+)/$', views.CourseDetail.as_view(), name='detail'),
    path("detail/<int:pk>/", views.CourseDetail.as_view(), name="detail"),
    path('all/', views.ListCourse.as_view(), name="list"),
    path('course_info/<int:pk>/', views.CourseInfoView.as_view(), name='course_info'),
    re_path(r'^enroll/(?P<pk>[-\w]+)/$', views.EnrollCourse.as_view(), name='enroll'),
    re_path(r'^unenroll/(?P<pk>[-\w]+)/$', views.UnenrollCourse.as_view(), name='unenroll'),
    path('create_chapter/', views.CreateChapterView.as_view(), name='create_chapter'),
    path('create_lesson/', views.CreateLessonView.as_view(), name='create_lesson'),
    path('update_chapter/<int:pk>/', views.UpdateChapterView.as_view(), name='update_chapter'),
    path('update_lesson/<int:pk>/', views.UpdateLessonView.as_view(), name='update_lesson'),
    path('update_course/<int:pk>/', views.UpdateCourseView.as_view(), name='update_course'),
    path('completed_lessons_count/<int:course_id>/', views.get_completed_lessons_count, name='completed_lesson_count'),
    # path('completed_lesson_count/<int:pk>/', views.CourseDetail.as_view(), name='completed_lesson_count'),
    path('mark_lesson_as_complete/', views.mark_lesson_as_complete, name='mark_lesson_as_complete'),
    path('certificate/<int:course_id>/', views.certificate_view, name='certificate'),
    path('update_video_progress/', views.update_video_progress, name='update_video_progress'),
    path('verify_certificate/', views.verify_certificate, name='verify_certificate'),
    path('achievements/', views.achievements, name='achievements'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url, include
from django.urls import re_path
from assignments import views
from django_lms import views as views_project
from django_lms import views as project_views
from graphene_django.views import GraphQLView
from django.views.decorators.cache import cache_page

from graphene_file_upload.django import FileUploadGraphQLView
from .views import get_calendar_events



urlpatterns = [
    re_path(r'^$', project_views.index, name="home"),
    path('admin/', admin.site.urls),
    re_path(r'^users/', include('users.urls', namespace='users')),
    re_path(r'^courses/', include('courses.urls', namespace="courses")),
    re_path(r'^assignments/', include('assignments.urls', namespace='assignments')),
    re_path(r'^resources/', include('resources.urls', namespace="resources")),
    re_path(r'^editor/', include('editor.urls', namespace="editor")),
    path('user_profile/<int:pk>/',cache_page(60*60)(project_views.UserProfile.as_view()), name='profile'),

    re_path('graphql/', FileUploadGraphQLView.as_view(graphiql=True)),
    path("__reload__/", include("django_browser_reload.urls")),
    path('send-chatbot-response/', views_project.send_chatbot_response, name='chattext'),
    path('markdownx/', include('markdownx.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('calendar/', get_calendar_events, name='calendar'),
    path('accounts/', include('allauth.urls')),


    # path('', include('admin_material.urls')),
    # path('api-auth/', include('rest_framework.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import re_path,path
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

urlpatterns = [
    # re_path(r'login/$', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    # re_path(r'logout/$', auth_views.LogoutView.as_view(), name="logout"),
    # re_path(r'signup/$', views.SignUp.as_view(), name='signup'),
    path('signup/', views.CustomSignUpView.as_view(), name='signup'),
    re_path(r'contact/$', views.Contact, name='contact'),
]

courses/forms.py
from django.forms import ModelForm
from courses.models import Course, Lesson, Chapter
from users.models import User
from django.shortcuts import get_object_or_404
from django import forms


class CreateChapterForm(ModelForm):
    class Meta:
        model = Chapter
        fields = ('chapter_name', 'chapter_description', 'course')
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        user_object = User.objects.filter(username = user.username)
        new_user_object = get_object_or_404(user_object)
        self.fields['course'].queryset = self.fields['course'].queryset.filter(teacher = new_user_object.id)
        # self.fields['chapter_quiz'].queryset = self.fields['chapter_quiz'].queryset.filter(course__teacher = new_user_object.id)

class CreateLessonForm(ModelForm):
    word_file = forms.FileField(
        label='Upload Word File',
        required=False,  # Set to False to make it optional
    )
    class Meta:
        model = Lesson
        fields = ('lesson_name', 'lesson_content', 'chapter', 'word_file')
        
        def __init__(self, *args, **kwargs):
            user = kwargs.pop('user')
            super().__init__(*args, **kwargs)
            user_object = User.objects.filter(username = user.username)
            new_user_object = get_object_or_404(user_object)
            self.fields['chapter'].queryset = self.fields['chapter'].queryset.filter(course__teacher = new_user_object.id)

class UpdateCourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ('course_name', 'course_description')
    
                
class UpdateChapterForm(ModelForm):
    class Meta:
        model = Chapter
        fields = ('chapter_name', 'chapter_description', 'course')
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        user_object = User.objects.filter(username = user.username)
        new_user_object = get_object_or_404(user_object)
        self.fields['course'].queryset = self.fields['course'].queryset.filter(teacher = new_user_object.id)


class UpdateLessonForm(ModelForm):
    class Meta:
        model = Lesson
        fields = ('lesson_name', 'lesson_content', 'chapter')
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        user_object = User.objects.filter(username = user.username)
        new_user_object = get_object_or_404(user_object)
        self.fields['chapter'].queryset = self.fields['chapter'].queryset.filter(course__teacher = new_user_object.id)

courses/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect,HttpResponseRedirect
import datetime
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.urls import reverse
from django.contrib import messages
from django.views import generic
from django.shortcuts import get_object_or_404
from users.models import User
from courses.models import Course, Enrollment, Lesson, Chapter, CompletedCourse, Certificate
from assignments.models import Assignment, Quiz
from resources.models import Resource, VideoLesson, VideoProgress
from .models import CompletedLesson
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.db import transaction
import datetime
import calendar
from .cert_request import send_certificate_request, verify_certificate
import json
from django.views import View
from django.http import JsonResponse
from .models import CompletedLesson, Course
from .forms import CreateChapterForm, CreateLessonForm, UpdateChapterForm, UpdateLessonForm, UpdateCourseForm
import mammoth
from django.views.decorators.csrf import csrf_protect
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.base import ContentFile
import io
from django.db import IntegrityError
from django.http import Http404
from assignments import models
from assignments.models import QuizSubmission, CompletedQuiz
from django.db.models import Count

# Create your views here.
class CreateCourse(LoginRequiredMixin, generic.CreateView):
    fields = ('course_name', 'course_description')
    model = Course

    def get(self, request,*args, **kwargs):
        self.object = None
        context_dict = self.get_context_data()
        context_dict.update(user_type=self.request.user.user_type)
        return self.render_to_response(context_dict)
    
    def form_valid(self, form):
        form.instance.teacher = self.request.user
        return super(CreateCourse, self).form_valid(form)
    
class CreateChapterView(LoginRequiredMixin, generic.CreateView):
    model = Chapter
    form_class = CreateChapterForm
    template_name = 'courses/create_chapter.html'
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs
    
    
    def form_valid(self, form):
        user_object = get_object_or_404(User, username=self.request.user.username)
        form.instance.teacher = user_object
        return super().form_valid(form)
    def get_success_url(self):
        url = reverse('courses:list')
        return url

class CreateLessonView(LoginRequiredMixin, generic.CreateView):
    form_class = CreateLessonForm
    template_name = 'courses/create_lesson.html'
  
    
    def get_from_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    def form_valid(self, form):
        user_object = get_object_or_404(User, username=self.request.user.username)
        form.instance.teacher = user_object
        word_file = form.cleaned_data['word_file']

        if word_file:
            if hasattr(word_file, 'read'):
                # File is in memory, read its content
                content = word_file.read()
                # Perform the Word to Markdown conversion
                result = mammoth.convert_to_markdown(io.BytesIO(content))
                form.instance.lesson_content = result.value
            else:
                # File is on disk, perform conversion as before
                with open(word_file.path, 'rb') as docx_file:
                    result = mammoth.convert_to_markdown(docx_file)
                    form.instance.lesson_content = result.value

        return super().form_valid(form)
    def get_success_url(self) -> str:
        return reverse('courses:list')

class CourseDetail(generic.DetailView):
    model = Course
    
    
    def get_context_data(self, **kwargs):
         # Initialize user_profile
        user_profile = None
        try:
            user_id = self.request.user.id
            # Attempt to get user_profile
            # user_profile = UserProfile.objects.get(user=self.request.user)
            course = get_object_or_404(Course, pk=self.kwargs['pk'])
        except Http404:
            # Handle the case where UserProfile does not exist
            pass
            # Handle the case where the course does not exist
            messages.error(self.request, 'Course not found.')
            return HttpResponseRedirect(reverse('courses:list')) 
        
        completed_lesson_ids = []
        
        # Get chapters related to the course
        chapters = Chapter.objects.filter(course=course)

        # chapters_with_lessons = {}
        
        # Create a dictionary to store chapters and their related lessons
        chapters_with_lessons = []
        chapters_with_lessons_and_quizzes = {}

        # Initialize chapters_with_completion as an empty list
        chapters_with_completion = []

        # Initialize completed_chapter_ids as an empty list
        completed_chapter_ids = []

        
        for chapter in chapters:
            # Get lessons related to the chapter
            lessons = Lesson.objects.filter(chapter=chapter)
            # get the count of lessons that exist in each chapter
            lesson_count = lessons.count()
            chapters_with_lessons.append((chapter, lessons))
            
            quizzes = Quiz.objects.filter(chapter=chapter)
            chapters_with_lessons_and_quizzes[chapter] = {
                'lessons': lessons,
                'quizzes': quizzes,
                'lesson_count': lesson_count,
            }

            print("Lesson Count: ", lesson_count)
            

            
        assignments = Assignment.objects.filter(course=self.kwargs['pk'])
        resources = Resource.objects.filter(course=self.kwargs['pk'])

        # Get the total number of lessons for the course
        total_lessons = Lesson.objects.filter(chapter__course=course).count()
        total_quizzes = course.total_quizzes()
        completed_quizzes_count = 0
        lesson_count = 0
        completion_status = False
        completed_courses = 0
        # Handle the case where total_lessons is zero
        if total_lessons > 0:
            # Get the total number of completed lessons for the user in that course
            if self.request.user.is_authenticated:
                user_id = self.request.user.id
                completed_lessons = CompletedLesson.objects.filter(user=user_id, lesson__chapter__course=course).count()

                completed_lessons = CompletedLesson.objects.filter(user=user_id, lesson__chapter__course=course).aggregate(count=Count('id'))['count']



                completion_percentage = round((completed_lessons / total_lessons) * 100)
                print("Completed Lessons:", completed_lessons)

                # Access and print the lesson IDs directly
                completed_lessons1 = CompletedLesson.objects.filter(user=user_id, lesson__chapter__course=course)
                completed_lesson_ids = [completed_lesson.lesson.id for completed_lesson in completed_lessons1]
                print("Lesson IDs completed:", completed_lesson_ids)

                # can i get the chapter ids
                completed_chapter_ids = [completed_lesson.lesson.chapter.id for completed_lesson in completed_lessons1]
                print("Chapter IDs completed:", completed_chapter_ids)

                # Create a list to store chapter information including completion status
                chapters_with_completion = []

            # create a list of completed courses
            completed_courses = []

            completed_quizzes = []
            

            # Check if the chapter ID occurs in completed chapter IDs and the count matches the lesson count
            for chapter in chapters:
                lessons = Lesson.objects.filter(chapter=chapter)
                # Get quizzes related to the chapter
                quizzes = Quiz.objects.filter(chapter=chapter)
                # get the count of lessons and quizzes that exist in each chapter
                lesson_count = lessons.count()
                quiz_count = quizzes.count()
                # Get the completed quiz IDs from the completedquiz model
                completed_quizzes = CompletedQuiz.objects.filter(user=user_id, quiz__chapter__course=course).values_list('quiz_id', flat=True)
                
                completed_quizzes_ids = set(completed_quizzes)

                # Check if all lessons and quizzes in the chapter are completed
                is_completed = all(
                    ((chapter.id in completed_chapter_ids and completed_chapter_ids.count(chapter.id) == lesson_count) and
                    (quiz.id in completed_quizzes_ids and len(completed_quizzes_ids.intersection([quiz.id])) == 1))
                    for quiz in quizzes
                )





                chapter_info = {
                    'chapter_id': chapter.id,
                    'lessons': lessons,
                    'quizzes': quizzes,
                    'is_completed': is_completed,
                }

                if is_completed:
                    chapters_with_completion.append(chapter_info)

            # Check if the total number of chapters equals the number of completed chapters for each course
            total_chapters = Chapter.objects.filter(course=course).count()

            completed_chapters_count = sum(1 for chapter_info in chapters_with_completion if chapter_info['is_completed'])
            print(f"Course: {course}, Total Chapters: {total_chapters}, Completed Chapters: {completed_chapters_count}")

            if total_chapters == completed_chapters_count:

courses/templates/courses/achievements.html
{% extends 'courses/course_base.html' %}
{% load static %}
{% block title %}
    {% block title_name %}
        Achievements
    {% endblock title_name %}
{% endblock title %}
{% block main_content %}
        <div class="h-auto p-2 w-auto mt-[150px]">
            <div class="container mx-auto mt-8">
                <h2 class="text-2xl font-semibold mb-4">Completed Courses</h2>
            
                <!-- Loop through completed courses and display them as cards or a detailed list -->
                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {% for completed_course in completed_courses %}
                        <div class="bg-white rounded-lg drop-shadow-lg p-6 mb-4">
                            <h3 class="text-lg font-semibold mb-2">{{ completed_course.course.course_name }}</h3>
                            <p class="text-gray-600">{{ completed_course.course.course_description }}</p>
                            <p class="text-sm text-gray-500 mt-2">Completed on {{ completed_course.completed_at|date }}</p>
                            <a href="{% url 'courses:certificate' course_id=completed_course.course.id %}">
                                <button id="generateCertificate" class="bg-yellow-500 text-white rounded-lg px-4 py-2 mt-4 hover:bg-yellow-400">
                                    Claim Certificate
                                </button>
                            </a> 
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    
{% endblock main_content %}

courses/templates/courses/course_base.html
{% extends 'base.html' %}

{% block title %}
    
    {% block title_name %}
        
    {% endblock title_name %}
        
{% endblock title %}
    
{% block body_content %}
    <div class="h-auto p-2 w-auto mt-[150px]">
        
        {% block main_content %}
            
        {% endblock main_content %}
            
    </div>
{% endblock body_content %}
    

courses/templates/courses/course_form.html
{% extends 'courses/course_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Create Course
{% endblock title_name %}
    

{% block main_content %}
<div class="ml-[50px] text-cyan-950 overflow-y-auto relative">
    <h1 class="font-sans font-extrabold text-3xl m-2">Create new Course</h1>
    
    {% if user_type == 2 %}
        <form action="{% url 'courses:create' %}" method="POST" class="shadow-lg p-4 rounded-xl font-sans font-semibold m-2">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Create" class="bg-cyan-950 m-2 text-white hover:bg-yellow-500 p-2 rounded-md text-md font-extrabold"/>
        </form>
    {% else %}
        <div class="jumbotron">
            <h2>Oops! You need to be Teacher to access this page.</h2>
        </div>
    </div>
    {% endif %}
        
{% endblock main_content %}
    

courses/templates/courses/course_info.html
<!-- templates/courses/course_info.html -->
{% extends 'courses/course_base.html' %}
{% block title_name %}
   LMS - {{ course.course_name }} Info
{% endblock title_name %}

{% block main_content %}
   <div class="ml-[50px] max-w-[72%] text-cyan-800 h-[830px] overflow-y-auto relative">
      <h1 class="font-sans font-semibold text-3xl m-2">{{ course.course_name }} - Course Overview</h1>
      <p class="font-sans text-lg m-2">{{ course.course_description }}</p>

      <h2 class="font-sans font-semibold text-2xl mt-4 mb-2">Modules:</h2>

      {% for chapter in chapters %}
         <h4 class="font-sans text-xl mb-2">{{ chapter.chapter_number }}. {{ chapter.chapter_name }}</h4>
         <div class="space-y-4">
            {% for lesson in chapter.lessons.all %}
               <div class="border p-4 rounded-md border-solid box-border ">
                  <i class="fa fa-icon-stm_icon_teacher"></i>
                  <h5 class="font-semibold text-lg"> {{ lesson.lesson_name }}</h5>
               
                
                  <div id="lesson{{ lesson.id }}" class="collapse mt-3">
                     <!-- Additional details or nested content for the lesson -->
                  </div>
               </div>
            {% endfor %}
         </div>
      {% endfor %}
   </div>
{% endblock main_content %}

courses/templates/courses/course_list.html
{% extends 'courses/course_base.html' %}
{% load static %}
{% load cache %}
{% block title_name %}
  LMS - Courses
{% endblock title_name %}

{% block main_content %}
<div class="max-w-[75%] mx-auto mt-0 lg:max-w-[95%] lg:relative lg:top-0 absolute top-[150px]  left-[50px]">
  <div class="lg:flex lg:flex-row lg:justify-between">
    <h1 class="font-semibold font-sans m-1 text-cyan-950">All Courses</h1>

    {% if user.user_type == 2 %}
      <a href="{% url 'courses:create' %}" class="bg-cyan-950 m-3 mb-2 lg:flex no-underline lg:flex-col text-white hover:bg-yellow-500 p-2 rounded-md text-md font-extrabold">
        <i class="fa fa-plus-circle" aria-hidden="true"> Create New Course</i>
      </a>
    {% endif %}
  </div>

  <div class="lg:card-deck lg:space-x-9 lg:w-[72%] flex flex-wrap">
    {% cache 600 "course_list" %}
      {% for course_item in object_list %}
        <div class="w-full lg:w-[48%] xl:w-[30%] mb-4">
          <div class="bg-white rounded-md bg-opacity-40 lg:w-[350px] relative shadow-lg h-auto m-2">
            <div class="card-body hover:shadow-2xl">
              <h5 class="card-title text-cyan-950 font-serif font-extrabold">{{course_item.course_name}}</h5>
              {% if course_item.picture %}
                <img src="{{ course_item.picture.url }}" alt="{{ course_item.course_name }}" class=" mb-3 card-img-top">
              {% else %}
                <!-- Default image or placeholder if no picture is available -->
                <img src="{% static 'django_lms/images/web4.jpg' %}" alt="Default Image" class="card-img-top">
              {% endif %}
              <h6 class="card-subtitle mb-2 text-muted">{{course_item.teacher}}</h6>
              <p class="card-text font-semibold">{{course_item.course_description}}</p>
              <a href="{% url 'courses:detail' pk=course_item.pk %}" class="bg-cyan-950 text-white m-5 p-2 hover:bg-yellow-400 rounded-md text-md font-extrabold ">More Info</a>

              {% if user.user_type == 1 %}
                {% if user in course_item.students.all %}
                  <a href="{% url 'courses:unenroll' pk=course_item.pk %}" class="bg-red-600 m-2 text-white hover:bg-red-800 p-2 rounded-md text-md font-extrabold card-link">Unenroll</a>
                {% else %}
                  <a href="{% url 'courses:enroll' pk=course_item.pk %}" class="bg-green-500 m-2 text-white hover:bg-green-800 p-2 rounded-md text-md font-extrabold card-link">Enroll</a>
                {% endif %}
              {% endif %}

              <p class="text-lg m-2">{{course_item.students.count}} member{{course_item.students.count|pluralize}}</p>
            </div>
          </div>
        </div>
      {% endfor %}
    {% endcache %}
  </div>
</div>
{% endblock main_content %}

courses/templates/courses/create_chapter.html
{% extends 'courses/course_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Create Chapter
{% endblock title_name %}
    

{% block main_content %}
<div class="ml-[50px] text-cyan-950 overflow-y-auto relative">
    <h1 class="font-sans font-semibold text-3xl m-2">Creating Course Chapters</h1>
  
    {% if user.user_type == 2 %}
      <form method="POST" action="{% url 'courses:create_chapter' %}" class="shadow-lg p-4 rounded-xl font-sans font-semibold m-2">
        {% csrf_token %} 
        {% bootstrap_field form.chapter_name %}
        {% bootstrap_field form.chapter_description %}
        {% bootstrap_field form.course %}
        {{ form.name.errors }}
        <input type="submit" value="Submit" class="bg-cyan-950 m-2 text-white hover:bg-yellow-500 p-2 rounded-md text-md font-extrabold hover:no-underline">
      </form>
      
      
      {% else %}
          <div class="jumbotron">
              <h2>You cannot create an assignment</h2>
          </div>
      {% endif %}
  
  </div>
        
{% endblock main_content %}
    

courses/templates/courses/create_lesson.html
{% extends 'courses/course_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Create Lesson
{% endblock title_name %}
    

{% block main_content %}
<div class="ml-[50px] text-cyan-950 overflow-y-auto relative">
    <h1 class="font-sans font-semibold text-3xl m-2">Creating Chapter lessons</h1>
  
    {% if user.user_type == 2 %}
      <form method="POST" action="{% url 'courses:create_lesson' %}" enctype="multipart/form-data" class="shadow-lg p-4 rounded-xl font-sans font-semibold m-2">
        {% csrf_token %} 
        {% bootstrap_field form.lesson_name %}
        {% bootstrap_field form.lesson_content %}
        {% bootstrap_field form.chapter %}
        {% bootstrap_field form.word_file %}
        {{ form.name.errors }}
        <input type="submit" value="Submit" class="bg-cyan-950 m-2 text-white hover:bg-yellow-500 p-2 rounded-md text-md font-extrabold hover:no-underline">
      </form>
      
      
      {% else %}
          <div class="jumbotron">
              <h2>You cannot create an assignment</h2>
          </div>
      {% endif %}
  
  </div>
        
{% endblock main_content %}
    

courses/templates/courses/update_chapter.html
{% extends 'courses/course_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Update Chapter
{% endblock title_name %}

{% block content %}
<div class="container">
    <h1 class="font-sans font-semibold text-3xl m-2">Updating Courses Chapters</h1>
  
    {% if user.user_type == 2 %}
      <form method="POST" action="{% url 'courses:update_chapter' %}" class="shadow-lg p-4 rounded-xl font-sans font-semibold m-2">
        {% csrf_token %} 
        {% bootstrap_field form.chapter_name %}
        {% bootstrap_field form.chapter_description %}
        {% bootstrap_field form.course %}
        {{ form.name.errors }}
        <input type="submit" value="Submit" class="bg-green-600 m-2 text-white hover:bg-green-800 p-2 rounded-md text-md font-extrabold hover:no-underline">
      </form>
      
      
      {% else %}
          <div class="jumbotron">
              <h2>You cannot update this Section</h2>
          </div>
      {% endif %}
  
  </div>
{% endblock %}

courses/templates/courses/update_course.html
{% extends 'courses/course_base.html' %}

{% load bootstrap4 %}

{% block title_name %}
    LMS - Update Course
{% endblock title_name %}

{% block content %}
<div class="container">
    <h1 class="font-sans font-semibold text-3xl m-2">Updating Course</h1>
  
    {% if user.user_type == 2 %}
      <form method="POST" action="{% url 'courses:update_course' %}" class="shadow-lg p-4 rounded-xl font-sans font-semibold m-2">
        {% csrf_token %} 
        {% bootstrap_field form.course_name %}
        {% bootstrap_field form.course_description %}
        {{ form.name.errors }}
        <input type="submit" value="Submit" class="bg-green-600 m-2 text-white hover:bg-green-800 p-2 rounded-md text-md font-extrabold hover:no-underline">
      </form>
      
      
      {% else %}
          <div class="jumbotron">
              <h2>You cannot update this Section </h2>
          </div>
      {% endif %}
  
  </div>
{% endblock %}

courses/templates/courses/update_lesson.html
{% extends 'courses/course_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Update Lesson
{% endblock title_name %}

{% block content %}
<div class="container">
    <h1 class="font-sans font-semibold text-3xl m-2">Updating Chapter lessons</h1>
  
    {% if user.user_type == 2 %}
      <form method="POST" action="{% url 'courses:update_lesson' %}" class="shadow-lg p-4 rounded-xl font-sans font-semibold m-2">
        {% csrf_token %} 
        {% bootstrap_field form.lesson_name %}
        {% bootstrap_field form.lesson_content %}
        {% bootstrap_field form.chapter %}
        {{ form.name.errors }}
        <input type="submit" value="Submit" class="bg-green-600 m-2 text-white hover:bg-green-800 p-2 rounded-md text-md font-extrabold hover:no-underline">
      </form>
      
      
      {% else %}
          <div class="jumbotron">
              <h2>You cannot update this Section </h2>
          </div>
      {% endif %}
  
  </div>
{% endblock %}