courses/urls.py
# from django.conf.urls import url
from django.urls import re_path, path
from courses import views

from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

app_name = "courses"

urlpatterns = [
    re_path(r'^new/$', views.CreateCourse.as_view(), name="create"),
    # re_path(r'^detail/(?P<pk>[-\w]+)/$', views.CourseDetail.as_view(), name='detail'),
    path("detail/<int:pk>/", views.CourseDetail.as_view(), name="detail"),
    path('all/', views.ListCourse.as_view(), name="list"),
    path('course_info/<int:pk>/', views.CourseInfoView.as_view(), name='course_info'),
    re_path(r'^enroll/(?P<pk>[-\w]+)/$', views.EnrollCourse.as_view(), name='enroll'),
    re_path(r'^unenroll/(?P<pk>[-\w]+)/$', views.UnenrollCourse.as_view(), name='unenroll'),
    path('create_chapter/', views.CreateChapterView.as_view(), name='create_chapter'),
    path('create_lesson/', views.CreateLessonView.as_view(), name='create_lesson'),
    path('update_chapter/<int:pk>/', views.UpdateChapterView.as_view(), name='update_chapter'),
    path('update_lesson/<int:pk>/', views.UpdateLessonView.as_view(), name='update_lesson'),
    path('update_course/<int:pk>/', views.UpdateCourseView.as_view(), name='update_course'),
    path('completed_lessons_count/<int:course_id>/', views.get_completed_lessons_count, name='completed_lesson_count'),
    # path('completed_lesson_count/<int:pk>/', views.CourseDetail.as_view(), name='completed_lesson_count'),
    path('mark_lesson_as_complete/', views.mark_lesson_as_complete, name='mark_lesson_as_complete'),
    path('certificate/<int:course_id>/', views.certificate_view, name='certificate'),
    path('update_video_progress/', views.update_video_progress, name='update_video_progress'),
    path('verify_certificate/', views.verify_certificate, name='verify_certificate'),
    path('achievements/', views.achievements, name='achievements'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url, include
from django.urls import re_path
from assignments import views
from django_lms import views as views_project
from django_lms import views as project_views
from graphene_django.views import GraphQLView
from django.views.decorators.cache import cache_page

from graphene_file_upload.django import FileUploadGraphQLView
from .views import get_calendar_events



urlpatterns = [
    re_path(r'^$', project_views.index, name="home"),
    path('admin/', admin.site.urls),
    re_path(r'^users/', include('users.urls', namespace='users')),
    re_path(r'^courses/', include('courses.urls', namespace="courses")),
    re_path(r'^assignments/', include('assignments.urls', namespace='assignments')),
    re_path(r'^resources/', include('resources.urls', namespace="resources")),
    re_path(r'^editor/', include('editor.urls', namespace="editor")),
    path('user_profile/<int:pk>/',cache_page(60*60)(project_views.UserProfile.as_view()), name='profile'),

    re_path('graphql/', FileUploadGraphQLView.as_view(graphiql=True)),
    path("__reload__/", include("django_browser_reload.urls")),
    path('send-chatbot-response/', views_project.send_chatbot_response, name='chattext'),
    path('markdownx/', include('markdownx.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('calendar/', get_calendar_events, name='calendar'),
    path('accounts/', include('allauth.urls')),


    # path('', include('admin_material.urls')),
    # path('api-auth/', include('rest_framework.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import re_path,path
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

urlpatterns = [
    # re_path(r'login/$', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    # re_path(r'logout/$', auth_views.LogoutView.as_view(), name="logout"),
    # re_path(r'signup/$', views.SignUp.as_view(), name='signup'),
    path('signup/', views.CustomSignUpView.as_view(), name='signup'),
    re_path(r'contact/$', views.Contact, name='contact'),
]

resources/templates/resources/create_resource_form.html
{% extends 'resources/resource_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Create Resource
{% endblock title_name %}
    

{% block main_content %}
    
<div class="container">
    <h1>Resource</h1>

    
    {% if user.user_type == 2 %}
        <form method="POST" action="{% url 'resources:create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {{ form.name.errors }}
            <input type="submit" value="Submit" class="bg-green-500 m-2 text-white hover:bg-green-800 p-2 rounded-md font-extrabold">
        </form>
    {% else %}
        <div class="jumbotron">
            <h2>You cannot create a resource</h2>
        </div>
    {% endif %}
        
</div>

{% endblock main_content %}
    

resources/templates/resources/resource_base.html
{% extends 'base.html' %}

{% block title %}
    {% block title_name %}
        Video Lesson
    {% endblock title_name %}
{% endblock title %}

{% block body_content %}
    {% block main_content %}
        <div id="player"></div>
        <p>video_id: {{ video_id }}</p>

        <script src="https://www.youtube.com/iframe_api"></script>
        <script>
            let player;
            let progressInterval;

            // Replace 'VIDEO_ID' with the actual YouTube video ID
            const videoId = '{{ video_id }}'

            function onYouTubeIframeAPIReady() {
                player = new YT.Player('player', {
                    height: '360', // Set the desired video height
                    width: '640',  // Set the desired video width
                    videoId: videoId,
                    events: {
                        'onReady': onPlayerReady,
                        'onStateChange': onPlayerStateChange
                    }
                });
            }

            function onPlayerReady(event) {
                event.target.playVideo();
                startProgressTracking();
            }

            function startProgressTracking() {
                progressInterval = setInterval(updateProgress, 10000); // Update progress every second
            }

            function updateProgress() {
                const currentTime = player.getCurrentTime();
                const duration = player.getDuration();
                const percentage = (currentTime / duration) * 100;

                // Update your progress bar or other UI elements with the 'percentage' value
                // For example, update a progress bar element with the calculated 'percentage'
                // document.getElementById('progress-bar').style.width = `${percentage}%`;

                // Send an AJAX POST request to update the progress
                const csrfToken = document.querySelector('input[name=csrfmiddlewaretoken]').value;

                fetch('/resources/update_video_progress/', {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'X-CSRFToken': csrfToken,
                  },
                  body: `video_id=${videoId}&progress=${percentage}`,
                })
                  .then((response) => response.json())
                  .then((data) => {
                    console.log(data.message); // Log the response message
                  })
                  .catch((error) => {
                    console.error('Error:', error);
                  });

            }

            function onPlayerStateChange(event) {
                if (event.data === YT.PlayerState.ENDED) {
                    clearInterval(progressInterval);
                    updateProgress(); // Ensure progress is 100% when the video ends
                }
            }
        </script>
    {% endblock main_content %}
{% endblock body_content %}

resources/templates/resources/resource_confirm_delete.html
{% extends 'resources/resource_base.html' %}

{% block title_name %}
    LMS - Confirmation
{% endblock title_name %}
    

{% block main_content %}
    {% if user.user_type == 2 %}
        <div class="container">
            <div class="jumbotron">
                <h2>Are you sure you want to delete this resource?</h2>
                <form method="post">
                    {% csrf_token %}
                    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
                    <a href="{% url 'courses:list' %}" class="btn btn-primary btn-large">Cancel</a>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h2>You are not allowed to delete a resource.</h2>
            </div>
        </div>
    {% endif %}
        
{% endblock main_content %}
    